language: go

go:
  - "1.12rc1"

env:
  - GO111MODULE=on GOPROXY=https://athens.azurefd.net/

before_install:
  - echo -e "machine api.github.com login douglarek password $GITHUB_TOKEN" >> ~/.netrc

script:
  - go build -v ./...
